%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-flexbe-behavior-engine
Version:        3.0.3
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS flexbe_behavior_engine package

License:        BSD
URL:            http://ros.org/wiki/flexbe
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-rolling-flexbe-core
Requires:       ros-rolling-flexbe-input
Requires:       ros-rolling-flexbe-mirror
Requires:       ros-rolling-flexbe-msgs
Requires:       ros-rolling-flexbe-onboard
Requires:       ros-rolling-flexbe-states
Requires:       ros-rolling-flexbe-testing
Requires:       ros-rolling-flexbe-widget
Requires:       ros-rolling-ros-workspace
BuildRequires:  ros-rolling-ament-cmake
BuildRequires:  ros-rolling-flexbe-core
BuildRequires:  ros-rolling-flexbe-input
BuildRequires:  ros-rolling-flexbe-mirror
BuildRequires:  ros-rolling-flexbe-msgs
BuildRequires:  ros-rolling-flexbe-onboard
BuildRequires:  ros-rolling-flexbe-states
BuildRequires:  ros-rolling-flexbe-testing
BuildRequires:  ros-rolling-flexbe-widget
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A meta-package to aggregate all the FlexBE packages

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/rolling" \
    -DAMENT_PREFIX_PATH="/opt/ros/rolling" \
    -DCMAKE_PREFIX_PATH="/opt/ros/rolling" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Thu Jun 06 2024 Philipp Schillinger <philsplus@gmail.com> - 3.0.3-1
- Autogenerated by Bloom

* Wed May 01 2024 Philipp Schillinger <philsplus@gmail.com> - 3.0.0-1
- Autogenerated by Bloom

