%{?!ros_distro:%global ros_distro rolling}
%global pkg_name flexbe_core
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-flexbe-core
Version:        4.1.4
Release:        1%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
URL:            http://ros.org/wiki/flexbe_core
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  python%{python3_pkgversion}-devel

%{?bloom_package}

%description
flexbe_core provides the core components for the FlexBE behavior engine.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
flexbe_core provides the core components for the FlexBE behavior engine.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
flexbe_core provides the core components for the FlexBE behavior engine.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%py3_build


%install
%py3_install -- --prefix "%{bloom_prefix}"


%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "^\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Sat May 16 2026 Philipp Schillinger <philsplus@gmail.com> - 4.1.4-1
- Autogenerated by Bloom

* Mon May 11 2026 Philipp Schillinger <philsplus@gmail.com> - 4.1.3-1
- Autogenerated by Bloom

* Tue Apr 28 2026 Philipp Schillinger <philsplus@gmail.com> - 4.0.3-2
- Autogenerated by Bloom

* Tue Apr 21 2026 Philipp Schillinger <philsplus@gmail.com> - 4.0.3-1
- Autogenerated by Bloom
